name: flutter_get_pattern_flutter_data
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get: ^3.26.0 # Gerenciamento de Estado
  flutter_data: ^0.7.1 # Banco de Dados, ORM e RestClient
  json_annotation: ^3.1.1
  flutter_data_json_api_adapter: ^0.1.11
  path_provider: ^1.6.28
  logger: ^0.9.4
  flutter_slidable: ^0.5.7
  random_color: ^1.0.5

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  build_runner: ^1.10.2
  json_serializable: ^3.5.1
  flutter_native_splash: ^0.3.2


  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
